//Width and height
var width = 600;
var height = 400;
var margin = {top: 20, right: 20, bottom: 20, left: 20};

//Get the dataset
var dataset = 
  {
    "nodes": [{
      "word": "a",
      "index": 0.0,
      "frequency": 4.0
    }, {
      "word": "above",
      "index": 1.0,
      "frequency": 1.0
    }, {
      "word": "aimless",
      "index": 2.0,
      "frequency": 1.0
    }, {
      "word": "all",
      "index": 3.0,
      "frequency": 1.0
    }, {
      "word": "and",
      "index": 4.0,
      "frequency": 6.0
    }, {
      "word": "are",
      "index": 5.0,
      "frequency": 2.0
    }, {
      "word": "at",
      "index": 6.0,
      "frequency": 1.0
    }, {
      "word": "beach",
      "index": 7.0,
      "frequency": 2.0
    }, {
      "word": "beads",
      "index": 8.0,
      "frequency": 1.0
    }, {
      "word": "bells",
      "index": 9.0,
      "frequency": 1.0
    }, {
      "word": "beneath",
      "index": 10.0,
      "frequency": 2.0
    }, {
      "word": "black",
      "index": 11.0,
      "frequency": 1.0
    }, {
      "word": "blades",
      "index": 12.0,
      "frequency": 1.0
    }, {
      "word": "blossom",
      "index": 13.0,
      "frequency": 1.0
    }, {
      "word": "blots",
      "index": 14.0,
      "frequency": 1.0
    }, {
      "word": "blue",
      "index": 15.0,
      "frequency": 9.0
    }, {
      "word": "blunt",
      "index": 16.0,
      "frequency": 2.0
    }, {
      "word": "boat",
      "index": 17.0,
      "frequency": 1.0
    }, {
      "word": "but",
      "index": 18.0,
      "frequency": 2.0
    }, {
      "word": "camels",
      "index": 19.0,
      "frequency": 1.0
    }, {
      "word": "cathedral's",
      "index": 20.0,
      "frequency": 1.0
    }, {
      "word": "centre",
      "index": 21.0,
      "frequency": 1.0
    }, {
      "word": "clog",
      "index": 22.0,
      "frequency": 1.0
    }, {
      "word": "closes",
      "index": 23.0,
      "frequency": 1.0
    }, {
      "word": "cold",
      "index": 24.0,
      "frequency": 1.0
    }, {
      "word": "columns",
      "index": 25.0,
      "frequency": 1.0
    }, {
      "word": "come",
      "index": 26.0,
      "frequency": 1.0
    }, {
      "word": "comes",
      "index": 27.0,
      "frequency": 1.0
    }, {
      "word": "cries",
      "index": 28.0,
      "frequency": 1.0
    }, {
      "word": "day",
      "index": 29.0,
      "frequency": 1.0
    }, {
      "word": "desert",
      "index": 30.0,
      "frequency": 1.0
    }, {
      "word": "different",
      "index": 31.0,
      "frequency": 1.0
    }, {
      "word": "down",
      "index": 32.0,
      "frequency": 1.0
    }, {
      "word": "downwards",
      "index": 33.0,
      "frequency": 1.0
    }, {
      "word": "dowsing",
      "index": 34.0,
      "frequency": 1.0
    }, {
      "word": "drip",
      "index": 35.0,
      "frequency": 1.0
    }, {
      "word": "drips",
      "index": 36.0,
      "frequency": 1.0
    }, {
      "word": "drop",
      "index": 37.0,
      "frequency": 1.0
    }, {
      "word": "drops",
      "index": 38.0,
      "frequency": 1.0
    }, {
      "word": "dry",
      "index": 39.0,
      "frequency": 1.0
    }, {
      "word": "edge",
      "index": 40.0,
      "frequency": 1.0
    }, {
      "word": "empty",
      "index": 41.0,
      "frequency": 1.0
    }, {
      "word": "evening",
      "index": 42.0,
      "frequency": 1.0
    }, {
      "word": "eyes",
      "index": 43.0,
      "frequency": 1.0
    }, {
      "word": "faint",
      "index": 44.0,
      "frequency": 1.0
    }, {
      "word": "feathers",
      "index": 45.0,
      "frequency": 1.0
    }, {
      "word": "fiery-white",
      "index": 46.0,
      "frequency": 1.0
    }, {
      "word": "fingers",
      "index": 47.0,
      "frequency": 2.0
    }, {
      "word": "flops",
      "index": 48.0,
      "frequency": 1.0
    }, {
      "word": "fringe",
      "index": 49.0,
      "frequency": 1.0
    }, {
      "word": "frog",
      "index": 50.0,
      "frequency": 1.0
    }, {
      "word": "glass",
      "index": 51.0,
      "frequency": 3.0
    }, {
      "word": "glittering",
      "index": 52.0,
      "frequency": 1.0
    }, {
      "word": "green",
      "index": 53.0,
      "frequency": 6.0
    }, {
      "word": "green's",
      "index": 54.0,
      "frequency": 1.0
    }, {
      "word": "hang",
      "index": 55.0,
      "frequency": 1.0
    }, {
      "word": "hard",
      "index": 56.0,
      "frequency": 1.0
    }, {
      "word": "harsh",
      "index": 57.0,
      "frequency": 1.0
    }, {
      "word": "he",
      "index": 58.0,
      "frequency": 2.0
    }, {
      "word": "heavy",
      "index": 59.0,
      "frequency": 1.0
    }, {
      "word": "here",
      "index": 60.0,
      "frequency": 1.0
    }, {
      "word": "hide",
      "index": 61.0,
      "frequency": 1.0
    }, {
      "word": "him",
      "index": 62.0,
      "frequency": 1.0
    }, {
      "word": "his",
      "index": 63.0,
      "frequency": 3.0
    }, {
      "word": "hover",
      "index": 64.0,
      "frequency": 1.0
    }, {
      "word": "in",
      "index": 65.0,
      "frequency": 2.0
    }, {
      "word": "incense",
      "index": 66.0,
      "frequency": 1.0
    }, {
      "word": "into",
      "index": 67.0,
      "frequency": 1.0
    }, {
      "word": "iron",
      "index": 68.0,
      "frequency": 1.0
    }, {
      "word": "it's",
      "index": 69.0,
      "frequency": 1.0
    }, {
      "word": "laden",
      "index": 70.0,
      "frequency": 1.0
    }, {
      "word": "lies",
      "index": 71.0,
      "frequency": 1.0
    }, {
      "word": "light",
      "index": 72.0,
      "frequency": 1.0
    }, {
      "word": "line",
      "index": 73.0,
      "frequency": 1.0
    }, {
      "word": "long",
      "index": 74.0,
      "frequency": 1.0
    }, {
      "word": "lurch",
      "index": 75.0,
      "frequency": 1.0
    }, {
      "word": "lustre",
      "index": 76.0,
      "frequency": 1.0
    }, {
      "word": "madonnas",
      "index": 77.0,
      "frequency": 1.0
    }, {
      "word": "mantelpiece",
      "index": 78.0,
      "frequency": 1.0
    }, {
      "word": "marble",
      "index": 79.0,
      "frequency": 3.0
    }, {
      "word": "metallic",
      "index": 80.0,
      "frequency": 1.0
    }, {
      "word": "monster",
      "index": 81.0,
      "frequency": 1.0
    }, {
      "word": "mouth",
      "index": 82.0,
      "frequency": 1.0
    }, {
      "word": "needles",
      "index": 83.0,
      "frequency": 2.0
    }, {
      "word": "night",
      "index": 84.0,
      "frequency": 2.0
    }, {
      "word": "no",
      "index": 85.0,
      "frequency": 1.0
    }, {
      "word": "nostrils",
      "index": 86.0,
      "frequency": 2.0
    }, {
      "word": "obtuse",
      "index": 87.0,
      "frequency": 1.0
    }, {
      "word": "ocean",
      "index": 88.0,
      "frequency": 1.0
    }, {
      "word": "of",
      "index": 89.0,
      "frequency": 14.0
    }, {
      "word": "off",
      "index": 90.0,
      "frequency": 1.0
    }, {
      "word": "on",
      "index": 91.0,
      "frequency": 3.0
    }, {
      "word": "out",
      "index": 92.0,
      "frequency": 1.0
    }, {
      "word": "over",
      "index": 93.0,
      "frequency": 3.0
    }, {
      "word": "palm",
      "index": 94.0,
      "frequency": 1.0
    }, {
      "word": "parakeets",
      "index": 95.0,
      "frequency": 1.0
    }, {
      "word": "pebbles",
      "index": 96.0,
      "frequency": 1.0
    }, {
      "word": "polished",
      "index": 97.0,
      "frequency": 1.0
    }, {
      "word": "pool",
      "index": 98.0,
      "frequency": 1.0
    }, {
      "word": "pools",
      "index": 99.0,
      "frequency": 2.0
    }, {
      "word": "ported",
      "index": 100.0,
      "frequency": 1.0
    }, {
      "word": "ribs",
      "index": 101.0,
      "frequency": 1.0
    }, {
      "word": "rises",
      "index": 102.0,
      "frequency": 1.0
    }, {
      "word": "rolls",
      "index": 103.0,
      "frequency": 1.0
    }, {
      "word": "rowing",
      "index": 104.0,
      "frequency": 1.0
    }, {
      "word": "ruffled",
      "index": 105.0,
      "frequency": 1.0
    }, {
      "word": "rushes",
      "index": 106.0,
      "frequency": 1.0
    }, {
      "word": "rusty",
      "index": 107.0,
      "frequency": 1.0
    }, {
      "word": "sand",
      "index": 108.0,
      "frequency": 1.0
    }, {
      "word": "scales",
      "index": 109.0,
      "frequency": 1.0
    }, {
      "word": "set",
      "index": 110.0,
      "frequency": 1.0
    }, {
      "word": "settle",
      "index": 111.0,
      "frequency": 1.0
    }, {
      "word": "shadow",
      "index": 112.0,
      "frequency": 1.0
    }, {
      "word": "sharp",
      "index": 113.0,
      "frequency": 1.0
    }, {
      "word": "shedding",
      "index": 114.0,
      "frequency": 1.0
    }, {
      "word": "ships",
      "index": 115.0,
      "frequency": 1.0
    }, {
      "word": "sings",
      "index": 116.0,
      "frequency": 1.0
    }, {
      "word": "sky",
      "index": 117.0,
      "frequency": 1.0
    }, {
      "word": "slides",
      "index": 118.0,
      "frequency": 1.0
    }, {
      "word": "slushing",
      "index": 119.0,
      "frequency": 1.0
    }, {
      "word": "snub-nosed",
      "index": 120.0,
      "frequency": 1.0
    }, {
      "word": "spouts",
      "index": 121.0,
      "frequency": 1.0
    }, {
      "word": "spray",
      "index": 122.0,
      "frequency": 1.0
    }, {
      "word": "stains",
      "index": 123.0,
      "frequency": 1.0
    }, {
      "word": "stars",
      "index": 124.0,
      "frequency": 1.0
    }, {
      "word": "strokes",
      "index": 125.0,
      "frequency": 1.0
    }, {
      "word": "sun",
      "index": 126.0,
      "frequency": 1.0
    }, {
      "word": "surface",
      "index": 127.0,
      "frequency": 2.0
    }, {
      "word": "sway",
      "index": 128.0,
      "frequency": 1.0
    }, {
      "word": "sweeps",
      "index": 129.0,
      "frequency": 1.0
    }, {
      "word": "tarpaulin",
      "index": 130.0,
      "frequency": 1.0
    }, {
      "word": "ten",
      "index": 131.0,
      "frequency": 1.0
    }, {
      "word": "the",
      "index": 132.0,
      "frequency": 41.0
    }, {
      "word": "their",
      "index": 133.0,
      "frequency": 2.0
    }, {
      "word": "them",
      "index": 134.0,
      "frequency": 3.0
    }, {
      "word": "there",
      "index": 135.0,
      "frequency": 2.0
    }, {
      "word": "through",
      "index": 136.0,
      "frequency": 3.0
    }, {
      "word": "thrown",
      "index": 137.0,
      "frequency": 1.0
    }, {
      "word": "to",
      "index": 138.0,
      "frequency": 2.0
    }, {
      "word": "too",
      "index": 139.0,
      "frequency": 1.0
    }, {
      "word": "trees",
      "index": 140.0,
      "frequency": 1.0
    }, {
      "word": "two",
      "index": 141.0,
      "frequency": 1.0
    }, {
      "word": "unbroken",
      "index": 142.0,
      "frequency": 1.0
    }, {
      "word": "upon",
      "index": 143.0,
      "frequency": 2.0
    }, {
      "word": "veils",
      "index": 144.0,
      "frequency": 1.0
    }, {
      "word": "water",
      "index": 145.0,
      "frequency": 3.0
    }, {
      "word": "wave",
      "index": 146.0,
      "frequency": 1.0
    }, {
      "word": "waves",
      "index": 147.0,
      "frequency": 1.0
    }, {
      "word": "weeds",
      "index": 148.0,
      "frequency": 1.0
    }, {
      "word": "which",
      "index": 149.0,
      "frequency": 1.0
    }, {
      "word": "white",
      "index": 150.0,
      "frequency": 1.0
    }, {
      "word": "with",
      "index": 151.0,
      "frequency": 2.0
    }, {
      "word": "wrecked",
      "index": 152.0,
      "frequency": 1.0
    }
  ],

  "links": [
  // Blue
  {
    "source": 0.0,
    "target": 15.0,
    "value": "44.5"
  }, {
    "source": 1.0,
    "target": 15.0,
    "value": "72"
  }, {
    "source": 2.0,
    "target": 15.0,
    "value": "13"
  }, {
    "source": 3.0,
    "target": 15.0,
    "value": "118"
  }, {
    "source": 4.0,
    "target": 15.0,
    "value": "39.66666667"
  }, {
    "source": 5.0,
    "target": 15.0,
    "value": "25"
  }, {
    "source": 6.0,
    "target": 15.0,
    "value": "41"
  }, {
    "source": 7.0,
    "target": 15.0,
    "value": "4"
  }, {
    "source": 8.0,
    "target": 15.0,
    "value": "3"
  }, {
    "source": 9.0,
    "target": 15.0,
    "value": "8"
  }, {
    "source": 10.0,
    "target": 15.0,
    "value": "6"
  }, {
    "source": 11.0,
    "target": 15.0,
    "value": "19"
  }, {
    "source": 12.0,
    "target": 15.0,
    "value": "96"
  }, {
    "source": 13.0,
    "target": 15.0,
    "value": "46"
  }, {
    "source": 14.0,
    "target": 15.0,
    "value": "2"
  }, {
    "source": 15.0,
    "target": 15.0,
    "value": "0"
  }, {
    "source": 16.0,
    "target": 15.0,
    "value": "11"
  }, {
    "source": 17.0,
    "target": 15.0,
    "value": "6"
  }, {
    "source": 18.0,
    "target": 15.0,
    "value": "45.5"
  }, {
    "source": 19.0,
    "target": 15.0,
    "value": "67"
  }, {
    "source": 20.0,
    "target": 15.0,
    "value": "5"
  }, {
    "source": 21.0,
    "target": 15.0,
    "value": "7"
  }, {
    "source": 22.0,
    "target": 15.0,
    "value": "53"
  }, {
    "source": 23.0,
    "target": 15.0,
    "value": "20"
  }, {
    "source": 24.0,
    "target": 15.0,
    "value": "4"
  }, {
    "source": 25.0,
    "target": 15.0,
    "value": "15"
  }, {
    "source": 26.0,
    "target": 15.0,
    "value": "15"
  }, {
    "source": 27.0,
    "target": 15.0,
    "value": "32"
  }, {
    "source": 28.0,
    "target": 15.0,
    "value": "98"
  }, {
    "source": 29.0,
    "target": 15.0,
    "value": "117"
  }, {
    "source": 30.0,
    "target": 15.0,
    "value": "70"
  }, {
    "source": 31.0,
    "target": 15.0,
    "value": "5"
  }, {
    "source": 32.0,
    "target": 15.0,
    "value": "127"
  }, {
    "source": 33.0,
    "target": 15.0,
    "value": "131"
  }, {
    "source": 34.0,
    "target": 15.0,
    "value": "17"
  }, {
    "source": 35.0,
    "target": 15.0,
    "value": "3"
  }, {
    "source": 36.0,
    "target": 15.0,
    "value": "80"
  }, {
    "source": 37.0,
    "target": 15.0,
    "value": "109"
  }, {
    "source": 38.0,
    "target": 15.0,
    "value": "123"
  }, {
    "source": 39.0,
    "target": 15.0,
    "value": "1"
  }, {
    "source": 40.0,
    "target": 15.0,
    "value": "56"
  }, {
    "source": 41.0,
    "target": 15.0,
    "value": "8"
  }, {
    "source": 42.0,
    "target": 15.0,
    "value": "33"
  }, {
    "source": 43.0,
    "target": 15.0,
    "value": "11"
  }, {
    "source": 44.0,
    "target": 15.0,
    "value": "1"
  }, {
    "source": 45.0,
    "target": 15.0,
    "value": "103"
  }, {
    "source": 46.0,
    "target": 15.0,
    "value": "11"
  }, {
    "source": 47.0,
    "target": 15.0,
    "value": "124"
  }, {
    "source": 48.0,
    "target": 15.0,
    "value": "43"
  }, {
    "source": 49.0,
    "target": 15.0,
    "value": "2"
  }, {
    "source": 50.0,
    "target": 15.0,
    "value": "44"
  }, {
    "source": 51.0,
    "target": 15.0,
    "value": "113"
  }, {
    "source": 52.0,
    "target": 15.0,
    "value": "88"
  }, {
    "source": 53.0,
    "target": 15.0,
    "value": "#DIV/0!"
  }, {
    "source": 54.0,
    "target": 15.0,
    "value": "2"
  }, {
    "source": 55.0,
    "target": 15.0,
    "value": "132"
  }, {
    "source": 56.0,
    "target": 15.0,
    "value": "82"
  }, {
    "source": 57.0,
    "target": 15.0,
    "value": "99"
  }, {
    "source": 58.0,
    "target": 15.0,
    "value": "6.5"
  }, {
    "source": 59.0,
    "target": 15.0,
    "value": "5"
  }, {
    "source": 60.0,
    "target": 15.0,
    "value": "51"
  }, {
    "source": 61.0,
    "target": 15.0,
    "value": "15"
  }, {
    "source": 62.0,
    "target": 15.0,
    "value": "18"
  }, {
    "source": 63.0,
    "target": 15.0,
    "value": "15.66666667"
  }, {
    "source": 64.0,
    "target": 15.0,
    "value": "73"
  }, {
    "source": 65.0,
    "target": 15.0,
    "value": "48"
  }, {
    "source": 66.0,
    "target": 15.0,
    "value": "3"
  }, {
    "source": 67.0,
    "target": 15.0,
    "value": "4"
  }, {
    "source": 68.0,
    "target": 15.0,
    "value": "4"
  }, {
    "source": 69.0,
    "target": 15.0,
    "value": "6"
  }, {
    "source": 70.0,
    "target": 15.0,
    "value": "2"
  }, {
    "source": 71.0,
    "target": 15.0,
    "value": "5"
  }, {
    "source": 72.0,
    "target": 15.0,
    "value": "129"
  }, {
    "source": 73.0,
    "target": 15.0,
    "value": "21"
  }, {
    "source": 74.0,
    "target": 15.0,
    "value": "116"
  }, {
    "source": 75.0,
    "target": 15.0,
    "value": "66"
  }, {
    "source": 76.0,
    "target": 15.0,
    "value": "110"
  }, {
    "source": 77.0,
    "target": 15.0,
    "value": "5"
  }, {
    "source": 78.0,
    "target": 15.0,
    "value": "23"
  }, {
    "source": 79.0,
    "target": 15.0,
    "value": "79.66666667"
  }, {
    "source": 80.0,
    "target": 15.0,
    "value": "1"
  }, {
    "source": 81.0,
    "target": 15.0,
    "value": "27"
  }, {
    "source": 82.0,
    "target": 15.0,
    "value": "10"
  }, {
    "source": 83.0,
    "target": 15.0,
    "value": "46.5"
  }, {
    "source": 84.0,
    "target": 15.0,
    "value": "23"
  }, {
    "source": 85.0,
    "target": 15.0,
    "value": "17"
  }, {
    "source": 86.0,
    "target": 15.0,
    "value": "12.5"
  }, {
    "source": 87.0,
    "target": 15.0,
    "value": "3"
  }, {
    "source": 88.0,
    "target": 15.0,
    "value": "18"
  }, {
    "source": 89.0,
    "target": 15.0,
    "value": "49"
  }, {
    "source": 90.0,
    "target": 15.0,
    "value": "5"
  }, {
    "source": 91.0,
    "target": 15.0,
    "value": "47.33333333"
  }, {
    "source": 92.0,
    "target": 15.0,
    "value": "1"
  }, {
    "source": 93.0,
    "target": 15.0,
    "value": "28.66666667"
  }, {
    "source": 94.0,
    "target": 15.0,
    "value": "94"
  }, {
    "source": 95.0,
    "target": 15.0,
    "value": "101"
  }, {
    "source": 96.0,
    "target": 15.0,
    "value": "14"
  }, {
    "source": 97.0,
    "target": 15.0,
    "value": "15"
  }, {
    "source": 98.0,
    "target": 15.0,
    "value": "121"
  }, {
    "source": 99.0,
    "target": 15.0,
    "value": "68"
  }, {
    "source": 100.0,
    "target": 15.0,
    "value": "136"
  }, {
    "source": 101.0,
    "target": 15.0,
    "value": "11"
  }, {
    "source": 102.0,
    "target": 15.0,
    "value": "26"
  }, {
    "source": 103.0,
    "target": 15.0,
    "value": "3"
  }, {
    "source": 104.0,
    "target": 15.0,
    "value": "7"
  }, {
    "source": 105.0,
    "target": 15.0,
    "value": "21"
  }, {
    "source": 106.0,
    "target": 15.0,
    "value": "57"
  }, {
    "source": 107.0,
    "target": 15.0,
    "value": "5"
  }, {
    "source": 108.0,
    "target": 15.0,
    "value": "69"
  }, {
    "source": 109.0,
    "target": 15.0,
    "value": "3"
  }, {
    "source": 110.0,
    "target": 15.0,
    "value": "36"
  }, {
    "source": 111.0,
    "target": 15.0,
    "value": "61"
  }, {
    "source": 112.0,
    "target": 15.0,
    "value": "29"
  }, {
    "source": 113.0,
    "target": 15.0,
    "value": "97"
  }, {
    "source": 114.0,
    "target": 15.0,
    "value": "2"
  }, {
    "source": 115.0,
    "target": 15.0,
    "value": "16"
  }, {
    "source": 116.0,
    "target": 15.0,
    "value": "6"
  }, {
    "source": 117.0,
    "target": 15.0,
    "value": "7"
  }, {
    "source": 118.0,
    "target": 15.0,
    "value": "128"
  }, {
    "source": 119.0,
    "target": 15.0,
    "value": "14"
  }, {
    "source": 120.0,
    "target": 15.0,
    "value": "29"
  }, {
    "source": 121.0,
    "target": 15.0,
    "value": "21"
  }, {
    "source": 122.0,
    "target": 15.0,
    "value": "6"
  }, {
    "source": 123.0,
    "target": 15.0,
    "value": "7"
  }, {
    "source": 124.0,
    "target": 15.0,
    "value": "38"
  }, {
    "source": 125.0,
    "target": 15.0,
    "value": "2"
  }, {
    "source": 126.0,
    "target": 15.0,
    "value": "85"
  }, {
    "source": 127.0,
    "target": 15.0,
    "value": "21.5"
  }, {
    "source": 128.0,
    "target": 15.0,
    "value": "11"
  }, {
    "source": 129.0,
    "target": 15.0,
    "value": "28"
  }, {
    "source": 130.0,
    "target": 15.0,
    "value": "18"
  }, {
    "source": 131.0,
    "target": 15.0,
    "value": "114"
  }, {
    "source": 132.0,
    "target": 15.0,
    "value": "47.7631579"
  }, {
    "source": 133.0,
    "target": 15.0,
    "value": "51"
  }, {
    "source": 134.0,
    "target": 15.0,
    "value": "57"
  }, {
    "source": 135.0,
    "target": 15.0,
    "value": "42"
  }, {
    "source": 136.0,
    "target": 15.0,
    "value": "32.66666667"
  }, {
    "source": 137.0,
    "target": 15.0,
    "value": "10"
  }, {
    "source": 138.0,
    "target": 15.0,
    "value": "51.5"
  }, {
    "source": 139.0,
    "target": 15.0,
    "value": "91"
  }, {
    "source": 140.0,
    "target": 15.0,
    "value": "93"
  }, {
    "source": 141.0,
    "target": 15.0,
    "value": "16"
  }, {
    "source": 142.0,
    "target": 15.0,
    "value": "34"
  }, {
    "source": 143.0,
    "target": 15.0,
    "value": "58"
  }, {
    "source": 144.0,
    "target": 15.0,
    "value": "3"
  }, {
    "source": 145.0,
    "target": 15.0,
    "value": "9.333333333"
  }, {
    "source": 146.0,
    "target": 15.0,
    "value": "4"
  }, {
    "source": 147.0,
    "target": 15.0,
    "value": "12"
  }, {
    "source": 148.0,
    "target": 15.0,
    "value": "54"
  }, {
    "source": 149.0,
    "target": 15.0,
    "value": "12"
  }, {
    "source": 150.0,
    "target": 15.0,
    "value": "47"
  }, {
    "source": 151.0,
    "target": 15.0,
    "value": "1"
  }, {
    "source": 152.0,
    "target": 15.0,
    "value": "8"
  },

  // Green
  {
    "source": 0.0,
    "target": 53.0,
    "value": "29.875"
  }, {
    "source": 1.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 2.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 3.0,
    "target": 53.0,
    "value": "5.5"
  }, {
    "source": 4.0,
    "target": 53.0,
    "value": "24.91666667"
  }, {
    "source": 5.0,
    "target": 53.0,
    "value": "42.25"
  }, {
    "source": 6.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 7.0,
    "target": 53.0,
    "value": "82"
  }, {
    "source": 8.0,
    "target": 53.0,
    "value": "34"
  }, {
    "source": 9.0,
    "target": 53.0,
    "value": "107"
  }, {
    "source": 10.0,
    "target": 53.0,
    "value": "36"
  }, {
    "source": 11.0,
    "target": 53.0,
    "value": "40"
  }, {
    "source": 12.0,
    "target": 53.0,
    "value": "8"
  }, {
    "source": 13.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 14.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 15.0,
    "target": 53.0,
    "value": "36.22222222"
  }, {
    "source": 16.0,
    "target": 53.0,
    "value": "45.5"
  }, {
    "source": 17.0,
    "target": 53.0,
    "value": "100"
  }, {
    "source": 18.0,
    "target": 53.0,
    "value": "57.5"
  }, {
    "source": 19.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 20.0,
    "target": 53.0,
    "value": "109"
  }, {
    "source": 21.0,
    "target": 53.0,
    "value": "26"
  }, {
    "source": 22.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 23.0,
    "target": 53.0,
    "value": "60"
  }, {
    "source": 24.0,
    "target": 53.0,
    "value": "111"
  }, {
    "source": 25.0,
    "target": 53.0,
    "value": "18"
  }, {
    "source": 26.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 27.0,
    "target": 53.0,
    "value": "45.5"
  }, {
    "source": 28.0,
    "target": 53.0,
    "value": "8"
  }, {
    "source": 29.0,
    "target": 53.0,
    "value": "5.5"
  }, {
    "source": 30.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 31.0,
    "target": 53.0,
    "value": "110"
  }, {
    "source": 32.0,
    "target": 53.0,
    "value": "35.5"
  }, {
    "source": 33.0,
    "target": 53.0,
    "value": "9.5"
  }, {
    "source": 34.0,
    "target": 53.0,
    "value": "63"
  }, {
    "source": 35.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 36.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 37.0,
    "target": 53.0,
    "value": "5.5"
  }, {
    "source": 38.0,
    "target": 53.0,
    "value": "9.5"
  }, {
    "source": 39.0,
    "target": 53.0,
    "value": "79"
  }, {
    "source": 40.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 41.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 42.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 43.0,
    "target": 53.0,
    "value": "69"
  }, {
    "source": 44.0,
    "target": 53.0,
    "value": "114"
  }, {
    "source": 45.0,
    "target": 53.0,
    "value": "8"
  }, {
    "source": 46.0,
    "target": 53.0,
    "value": "23"
  }, {
    "source": 47.0,
    "target": 53.0,
    "value": "8.5"
  }, {
    "source": 48.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 49.0,
    "target": 53.0,
    "value": "31"
  }, {
    "source": 50.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 51.0,
    "target": 53.0,
    "value": "17"
  }, {
    "source": 52.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 53.0,
    "target": 53.0,
    "value": "0"
  }, {
    "source": 54.0,
    "target": 53.0,
    "value": "0"
  }, {
    "source": 55.0,
    "target": 53.0,
    "value": "9.5"
  }, {
    "source": 56.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 57.0,
    "target": 53.0,
    "value": "8"
  }, {
    "source": 58.0,
    "target": 53.0,
    "value": "63"
  }, {
    "source": 59.0,
    "target": 53.0,
    "value": "54"
  }, {
    "source": 60.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 61.0,
    "target": 53.0,
    "value": "44"
  }, {
    "source": 62.0,
    "target": 53.0,
    "value": "62"
  }, {
    "source": 63.0,
    "target": 53.0,
    "value": "41.66666667"
  }, {
    "source": 64.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 65.0,
    "target": 53.0,
    "value": "42.5"
  }, {
    "source": 66.0,
    "target": 53.0,
    "value": "112"
  }, {
    "source": 67.0,
    "target": 53.0,
    "value": "29"
  }, {
    "source": 68.0,
    "target": 53.0,
    "value": "88"
  }, {
    "source": 69.0,
    "target": 53.0,
    "value": "13.5"
  }, {
    "source": 70.0,
    "target": 53.0,
    "value": "113"
  }, {
    "source": 71.0,
    "target": 53.0,
    "value": "75"
  }, {
    "source": 72.0,
    "target": 53.0,
    "value": "9.5"
  }, {
    "source": 73.0,
    "target": 53.0,
    "value": "38"
  }, {
    "source": 74.0,
    "target": 53.0,
    "value": "5.5"
  }, {
    "source": 75.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 76.0,
    "target": 53.0,
    "value": "5.5"
  }, {
    "source": 77.0,
    "target": 53.0,
    "value": "120"
  }, {
    "source": 78.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 79.0,
    "target": 53.0,
    "value": "24"
  }, {
    "source": 80.0,
    "target": 53.0,
    "value": "83"
  }, {
    "source": 81.0,
    "target": 53.0,
    "value": "6"
  }, {
    "source": 82.0,
    "target": 53.0,
    "value": "49"
  }, {
    "source": 83.0,
    "target": 53.0,
    "value": "23"
  }, {
    "source": 84.0,
    "target": 53.0,
    "value": "23"
  }, {
    "source": 85.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 86.0,
    "target": 53.0,
    "value": "33.5"
  }, {
    "source": 87.0,
    "target": 53.0,
    "value": "77"
  }, {
    "source": 88.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 89.0,
    "target": 53.0,
    "value": "#DIV/0!"
  }, {
    "source": 90.0,
    "target": 53.0,
    "value": "28"
  }, {
    "source": 91.0,
    "target": 53.0,
    "value": "66.25"
  }, {
    "source": 92.0,
    "target": 53.0,
    "value": "1"
  }, {
    "source": 93.0,
    "target": 53.0,
    "value": "29.25"
  }, {
    "source": 94.0,
    "target": 53.0,
    "value": "8"
  }, {
    "source": 95.0,
    "target": 53.0,
    "value": "8"
  }, {
    "source": 96.0,
    "target": 53.0,
    "value": "66"
  }, {
    "source": 97.0,
    "target": 53.0,
    "value": "65"
  }, {
    "source": 98.0,
    "target": 53.0,
    "value": "9.5"
  }, {
    "source": 99.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 100.0,
    "target": 53.0,
    "value": "9.5"
  }, {
    "source": 101.0,
    "target": 53.0,
    "value": "95"
  }, {
    "source": 102.0,
    "target": 53.0,
    "value": "7"
  }, {
    "source": 103.0,
    "target": 53.0,
    "value": "103"
  }, {
    "source": 104.0,
    "target": 53.0,
    "value": "99"
  }, {
    "source": 105.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 106.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 107.0,
    "target": 53.0,
    "value": "87"
  }, {
    "source": 108.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 109.0,
    "target": 53.0,
    "value": "81"
  }, {
    "source": 110.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 111.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 112.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 113.0,
    "target": 53.0,
    "value": "8"
  }, {
    "source": 114.0,
    "target": 53.0,
    "value": "78"
  }, {
    "source": 115.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 116.0,
    "target": 53.0,
    "value": "53"
  }, {
    "source": 117.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 118.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 119.0,
    "target": 53.0,
    "value": "45"
  }, {
    "source": 120.0,
    "target": 53.0,
    "value": "5"
  }, {
    "source": 121.0,
    "target": 53.0,
    "value": "12"
  }, {
    "source": 122.0,
    "target": 53.0,
    "value": "27"
  }, {
    "source": 123.0,
    "target": 53.0,
    "value": "85"
  }, {
    "source": 124.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 125.0,
    "target": 53.0,
    "value": "35"
  }, {
    "source": 126.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 127.0,
    "target": 53.0,
    "value": "16"
  }, {
    "source": 128.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 129.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 130.0,
    "target": 53.0,
    "value": "41"
  }, {
    "source": 131.0,
    "target": 53.0,
    "value": "5.5"
  }, {
    "source": 132.0,
    "target": 53.0,
    "value": "#DIV/0!"
  }, {
    "source": 133.0,
    "target": 53.0,
    "value": "82"
  }, {
    "source": 134.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 135.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 136.0,
    "target": 53.0,
    "value": "34.75"
  }, {
    "source": 137.0,
    "target": 53.0,
    "value": "70"
  }, {
    "source": 138.0,
    "target": 53.0,
    "value": "30"
  }, {
    "source": 139.0,
    "target": 53.0,
    "value": "1"
  }, {
    "source": 140.0,
    "target": 53.0,
    "value": "8"
  }, {
    "source": 141.0,
    "target": 53.0,
    "value": "17"
  }, {
    "source": 142.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 143.0,
    "target": 53.0,
    "value": "43.5"
  }, {
    "source": 144.0,
    "target": 53.0,
    "value": "118"
  }, {
    "source": 145.0,
    "target": 53.0,
    "value": "41"
  }, {
    "source": 146.0,
    "target": 53.0,
    "value": "103"
  }, {
    "source": 147.0,
    "target": 53.0,
    "value": "14"
  }, {
    "source": 148.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 149.0,
    "target": 53.0,
    "value": "21"
  }, {
    "source": 150.0,
    "target": 53.0,
    "value": "32"
  }, {
    "source": 151.0,
    "target": 53.0,
    "value": "85.5"
  }, {
    "source": 152.0,
    "target": 53.0,
    "value": "98"
  }
  ]
};

var linksScale = d3.scale.sqrt()
                    .domain([0,200])
                    .range([10,0])

//Initialize force layout
var force = d3.layout.force()
     .size([width, height])
     .linkDistance([200])
     .charge([-100]);

//Create SVG element
var svg = d3.select("#sproingcanvas")
   .append("div")
   .classed("svg-container", true) //container class to make it responsive
   .append("svg")
   .attr("preserveAspectRatio", "xMinYMin meet")
   .attr("viewBox", "0 0 600 400")
   .classed("svg-content-responsive", true); 
   
//Create dataset structure
force.nodes(dataset.nodes)
.links(dataset.links)
.start();

// Declare tooltip
var div = d3.select("body").append("div")   
            .attr("class", "tooltip")               
            .style("opacity", 0);

// Assign colors to groups
var colors = function(dataset){
  if (dataset.group === "none") {
    return "#949494";
  } else if (dataset.group === "red") {
    return "#ff0000";
  } else if (dataset.group === "blue") {
    return "#00A6FF";
  } else if (dataset.group === "orange") {
    return "#FFA200";
  } else if (dataset.group === "purple") {
    return "#BB00FF";
  } else if (dataset.group === "green") {
    return "#00B539";
  } else {
    return "#000000";
  }
}; 

//Create links as lines
var link = svg.selectAll(".link")
  .data(dataset.links)
  .enter()
  .append("line")
  .attr("class", "link")
  .style("stroke", "#ccc")
  .style("stroke-width", function(d) {
    return linksScale(d.value);
  });

//Create nodes as circles
var node = svg.selectAll(".node")
  .data(dataset.nodes)
  .enter()
  .append("circle")
  .attr("class", "node")
  .attr("r", function(d) {
    return d.frequency;
  })
  .style("fill", colors)
  .call(force.drag)
  // Update label box
  .on("mouseover", function(d) {
      div.transition()
         .duration(200)      
         .style("opacity", 0.85);
      div.html("word:" + d.word + "<br/> frequency:" + d.frequency)
         .style("left", (d3.event.pageX) + "px")     
         .style("top", (d3.event.pageY - 28) + "px");
   })
   .on("mouseout", function(d) {
      div.transition()        
      .duration(1000)      
      .style("opacity", 0);
   })
   .on('dblclick', connectedNodes);

//Every time the simulation "ticks", this will be called
force.on("tick", function() {

  link.attr("x1", function(d) { return d.source.x; })
     .attr("y1", function(d) { return d.source.y; })
     .attr("x2", function(d) { return d.target.x; })
     .attr("y2", function(d) { return d.target.y; });

  node.attr("cx", function(d) { return d.x; })
     .attr("cy", function(d) { return d.y; });  
});

//---Insert-------

//Toggle stores whether the highlighting is on
var toggle = 0;

//Create an array logging what is connected to what
var linkedByIndex = {};
for (i = 0; i < dataset.nodes.length; i++) {
    linkedByIndex[i + "," + i] = 1;
};
dataset.links.forEach(function (d) {
    linkedByIndex[d.source.index + "," + d.target.index] = 1;
});

//This function looks up whether a pair are neighbours  
function neighboring(a, b) {
    return linkedByIndex[a.index + "," + b.index];
}

function connectedNodes() {

    if (toggle == 0) {
        //Reduce the opacity of all but the neighbouring nodes
        d = d3.select(this).node().__data__;
        node.style("opacity", function (o) {
            return neighboring(d, o) | neighboring(o, d) ? 1 : 0.1;
        });
        
        link.style("opacity", function (o) {
            return d.index==o.source.index | d.index==o.target.index ? 1 : 0.1;
        });
        
        //Reduce the op
        
        toggle = 1;
    } else {
        //Put them back to opacity=1
        node.style("opacity", 1);
        link.style("opacity", 1);
        toggle = 0;
    }

}

//---End Insert---